// The code below was generated by initiating codegen,
// Stopping the recording, manually navigating to the login page,
// logging in, and then starting the recording again.

import { test, expect } from '@playwright/test';
// import { beforeEach } from 'node:test';
// The above line was auto-generated by VS Code and is not needed.

test.describe('Make appointment', () => {
    test.beforeEach('Login with valid creds', async ({ page }) => {
        await page.goto('https://katalon-demo-cura.herokuapp.com/');
        await expect(page).toHaveTitle('CURA Healthcare Service');
        await expect(page.locator('//h1')).toHaveText('CURA Healthcare Service');

        // Click on 'Make Appointment' link
        await page.getByRole('link', { name: 'Make Appointment' }).click();
        // assert that 'Please login to make' will be visible
        await expect(page.getByText('Please login to make')).toBeVisible();

        // Successful login
        await page.getByLabel('Username').fill('John Doe');
        await page.getByLabel('Password').fill('ThisIsNotAPassword');
        await page.getByRole('button', { name: 'Login' }).click();
    });

    // Tests go here
    test('Should make an appointment with non-default values', async ({ page }, testInfo) => {
        
        console.log(`>> Current config \n: ${JSON.stringify(testInfo.config)}`);
        
        // dropdown
        await page.getByLabel('Facility').selectOption('Hongkong CURA Healthcare Center');

        // checkbox
        await page.getByRole('checkbox', { name: 'Apply for hospital readmission' }).check();

        // radio button
        await page.getByRole('radio', { name: 'Medicaid' }).check();

        // date input
        await page.getByRole('textbox', { name: 'Visit Date (Required)' }).click();
        await page.getByRole('textbox', { name: 'Visit Date (Required)' }).fill('05/10/2027');
        await page.getByRole('textbox', { name: 'Visit Date (Required)' }).press('Enter');

        // multi-line comment text
        await page.getByRole('textbox', { name: 'Comment' }).click();
        await page.getByRole('textbox', { name: 'Comment' }).fill('This is a multi-line comment\ncaptured by Playwright codegen');

        // click Book Appointment button
        await page.getByRole('button', { name: 'Book Appointment' }).click();

        // Verify successful login (assertions)
        await expect(page.locator('h2')).toContainText('Appointment Confirmation');
        await expect(page.getByRole('link', { name: 'Go to Homepage' })).toBeVisible();
    });
    // More tests go here
});

// The code code below was originally generated via codegen and then copied/pasted into the test block.
// We omitted the goto URL line because it's already included in the login code.
// I also removed the redundant steps captured during recording that weren't necessary (field focus, etc.)
// Then I commented out the code below.
// test("test", async ({ page }) => {
//   await page.goto('https://katalon-demo-cura.herokuapp.com/');
//   await page.getByLabel('Facility').selectOption('Hongkong CURA Healthcare Center');
//   await page.getByRole('checkbox', { name: 'Apply for hospital readmission' }).check();
//   await page.getByRole('radio', { name: 'Medicaid' }).check();
//   await page.getByRole('radio', { name: 'Medicaid' }).check();
//   await page.getByRole('textbox', { name: 'Visit Date (Required)' }).click();
//   await page.getByRole('textbox', { name: 'Visit Date (Required)' }).fill('05/10/2027');
//   await page.getByRole('textbox', { name: 'Visit Date (Required)' }).press('Enter');
//   await page.getByRole('textbox', { name: 'Comment' }).click();
//   await page.getByRole('textbox', { name: 'Comment' }).fill('This is a multi-line comment\ncaptured by Playwright codegen');
//   await page.getByRole('button', { name: 'Book Appointment' }).click();
//   await expect(page.locator('h2')).toContainText('Appointment Confirmation');
//   await expect(page.getByRole('link', { name: 'Go to Homepage' })).toBeVisible();
// });
