// The code below was generated by initiating codegen,
// Stopping the recording, manually navigating to the login page,
// logging in, and then starting the recording again.

import { test, expect } from '@playwright/test';
import { log } from '../helpers/logger.js';
import MakeAppointmentPage from '../page-objects/make-appointment.page.js';
// import { beforeEach } from 'node:test';
// The above line was auto-generated by VS Code and is not needed.

test.describe('Make appointment', () => {
    test.beforeEach('Login with valid creds', async ({ page }, testInfo) => {
        const envConfig = testInfo.project.use as any;
        // Get the URL from the config file.

        // Custom logs
        await log('info', `Launching the web application in ${envConfig.envName}`);

        await page.goto(envConfig.appURL);
        // await page.goto('https://katalon-demo-cura.herokuapp.com/');
        await expect(page).toHaveTitle('CURA Healthcare Service');
        await expect(page.locator('//h1')).toHaveText('CURA Healthcare Service');

        // Click on 'Make Appointment' link
        await page.getByRole('link', { name: 'Make Appointment' }).click();
        // assert that 'Please login to make' will be visible
        await expect(page.getByText('Please login to make')).toBeVisible();
        await log('info', 'Login page is visible');
        await log('error', 'The login page did not load correctly'); // Not a true error, just demonstrating the log function.

        // Log in using credentials loaded from the project's .env file.
        //
        // dotenv loads the .env values into Node.js's process.env object before the
        // test executes. This keeps sensitive data separate from the test code.
        //
        // process.env.TEST_USER_NAME retrieves the value assigned to TEST_USER_NAME.
        // process.env.TEST_PASSWORD retrieves the value assigned to TEST_PASSWORD.
        await page.getByLabel('Username').fill(process.env.TEST_USER_NAME);
        await page.getByLabel('Password').fill(process.env.TEST_PASSWORD);
        await page.getByRole('button', { name: 'Login' }).click();
    });

    // Tests go here
    test('Should make an appointment with non-default values', async ({ page }, testInfo) => {
        const makeAppointmentPage = new MakeAppointmentPage(page);

        // Display the complete Playwright configuration in the console.
        //
        // This was useful when learning how environment-specific configuration files
        // are loaded. Since this lesson focuses on handling sensitive data, we'll
        // temporarily disable this output to keep the console easier to read.
        //
        // Uncomment the line below if you need to troubleshoot configuration settings
        // in the future.
        //
        // console.log(`>> Current config \n: ${JSON.stringify(testInfo.config)}`);

        // dropdown
        await makeAppointmentPage.selectFacility('Hongkong CURA Healthcare Center');
        // checkbox
        await makeAppointmentPage.setReadmissionCheckbox(true);

        // radio button
        await makeAppointmentPage.selectHealthcareProgram('Medicaid');

        // date input
        await makeAppointmentPage.setVisitDate('05/10/2027');
       

        // multi-line comment text
        await makeAppointmentPage.setComment('This is a test comment');

        // click Book Appointment button
        await makeAppointmentPage.clickBookAppointment();

        // Verify that the appointment was created successfully.
        await expect(page.locator('h2')).toContainText('Appointment Confirmation');
        await expect(page.getByRole('link', { name: 'Go to Homepage' })).toBeVisible();
    });
    // More tests go here
});

// The code code below was originally generated via codegen and then copied/pasted into the test block.
// We omitted the goto URL line because it's already included in the login code.
// I also removed the redundant steps captured during recording that weren't necessary (field focus, etc.)
// Then I commented out the code below.
// test("test", async ({ page }) => {
//   await page.goto('https://katalon-demo-cura.herokuapp.com/');
//   await page.getByLabel('Facility').selectOption('Hongkong CURA Healthcare Center');
//   await page.getByRole('checkbox', { name: 'Apply for hospital readmission' }).check();
//   await page.getByRole('radio', { name: 'Medicaid' }).check();
//   await page.getByRole('radio', { name: 'Medicaid' }).check();
//   await page.getByRole('textbox', { name: 'Visit Date (Required)' }).click();
//   await page.getByRole('textbox', { name: 'Visit Date (Required)' }).fill('05/10/2027');
//   await page.getByRole('textbox', { name: 'Visit Date (Required)' }).press('Enter');
//   await page.getByRole('textbox', { name: 'Comment' }).click();
//   await page.getByRole('textbox', { name: 'Comment' }).fill('This is a multi-line comment\ncaptured by Playwright codegen');
//   await page.getByRole('button', { name: 'Book Appointment' }).click();
//   await expect(page.locator('h2')).toContainText('Appointment Confirmation');
//   await expect(page.getByRole('link', { name: 'Go to Homepage' })).toBeVisible();
// });
