// The code below was generated by initiating codegen,
// Stopping the recording, manually navigating to the login page,
// logging in, and then starting the recording again.

import { test, expect } from '@playwright/test';
// import { beforeEach } from 'node:test';
// The above line was auto-generated by VS Code and is not needed.

// Example of annotation at the 'describe' level (for this suite of tests).
// Annotations will be displayed at the top of the Playwright test report.
// In the Allure report they will be displayed when we drill down to the executed steps in a test.
test.describe('Make appointment', { annotation: { type: 'Story', description: 'JIRA-1234: Make appointment feature' } }, () => {
    test.beforeEach('Login with valid creds', async ({ page }, testInfo) => {
        await page.goto('https://katalon-demo-cura.herokuapp.com/');
        await expect(page).toHaveTitle('CURA Healthcare Service');
        await expect(page.locator('//h1')).toHaveText('CURA Healthcare Service');

        // Click on 'Make Appointment' link
        await page.getByRole('link', { name: 'Make Appointment' }).click();
        // Verify that the login instructions are visible
        await expect(page.getByText('Please login to make')).toBeVisible();

        // Log in with valid credentials
        await page.getByLabel('Username').fill('John Doe');
        await page.getByLabel('Password').fill('ThisIsNotAPassword');
        await page.getByRole('button', { name: 'Login' }).click();

        /**
         * Capture and attach a screenshot after successful login
         * @TODO Add this as a helper function.
         */
        const fullPageLoginScreenshot = await page.screenshot({ fullPage: true });
        await testInfo.attach('appointment page after successful login', {
            body: fullPageLoginScreenshot,
            contentType: 'image/png',
        });
    });

    // Tests go here
    // Example of annotation at the 'test' level (for individual tests within a suite.)
    // Also an example of a tag (tag: "@smoke"). This can be used to only execute tests tagged as @smoke if desired.
    test(
        'Should make an appointment with non-default values',
        { annotation: { type: 'Bug', description: 'Defect 1234 - does not work in Firefox.' }, tag: '@smoke' },
        // Added browserName fixture to the test.
        async ({ page, browserName }) => {
            // skip the test for Firefox
            test.skip(browserName === 'firefox', 'Open bug ID: 1234');

            // dropdown
            await page.getByLabel('Facility').selectOption('Hongkong CURA Healthcare Center');

            // checkbox
            await page.getByRole('checkbox', { name: 'Apply for hospital readmission' }).check();

            // radio button
            await page.getByRole('radio', { name: 'Medicaid' }).check();

            // date input
            await page.getByRole('textbox', { name: 'Visit Date (Required)' }).click();
            await page.getByRole('textbox', { name: 'Visit Date (Required)' }).fill('05/10/2027');
            // Intentionally comment out the next line to demonstrate automatic screenshot capture after a test failure
            await page.getByRole('textbox', { name: 'Visit Date (Required)' }).press('Enter');

            // multi-line comment text
            await page.getByRole('textbox', { name: 'Comment' }).click();
            await page.getByRole('textbox', { name: 'Comment' }).fill('This is a multi-line comment\ncaptured by Playwright codegen');

            // click Book Appointment button
            await page.getByRole('button', { name: 'Book Appointment' }).click();

            // Verify that the appointment was created successfully
            await expect(page.locator('h2')).toContainText('Appointment Confirmation');
            await expect(page.getByRole('link', { name: 'Go to Homepage' })).toBeVisible();
        }
    );
    // More tests go here
});

// The code below was originally generated via codegen and then copied/pasted into the test block.
// We omitted the goto URL line because it's already included in the login code.
// I also removed the redundant steps captured during recording that weren't necessary (field focus, etc.)
// Then I commented out the code below.
// test("test", async ({ page }) => {
//   await page.goto('https://katalon-demo-cura.herokuapp.com/');
//   await page.getByLabel('Facility').selectOption('Hongkong CURA Healthcare Center');
//   await page.getByRole('checkbox', { name: 'Apply for hospital readmission' }).check();
//   await page.getByRole('radio', { name: 'Medicaid' }).check();
//   await page.getByRole('radio', { name: 'Medicaid' }).check();
//   await page.getByRole('textbox', { name: 'Visit Date (Required)' }).click();
//   await page.getByRole('textbox', { name: 'Visit Date (Required)' }).fill('05/10/2027');
//   await page.getByRole('textbox', { name: 'Visit Date (Required)' }).press('Enter');
//   await page.getByRole('textbox', { name: 'Comment' }).click();
//   await page.getByRole('textbox', { name: 'Comment' }).fill('This is a multi-line comment\ncaptured by Playwright codegen');
//   await page.getByRole('button', { name: 'Book Appointment' }).click();
//   await expect(page.locator('h2')).toContainText('Appointment Confirmation');
//   await expect(page.getByRole('link', { name: 'Go to Homepage' })).toBeVisible();
// });
