// ============================================================================
// This script demonstrates data-driven testing using an external CSV file.
//
// Rather than hard-coding test values directly into the test, we use the
// reusable fileHelper.readCSV() function to read and parse appointment data
// from an external CSV file.
//
// Each row in the CSV file becomes one JavaScript object representing an
// appointment dataset, and Playwright automatically generates a separate
// test for every object in the returned array.
// ============================================================================

// The code below was generated by initiating codegen,
// stopping the recording, manually navigating to the login page,
// logging in, and then starting the recording again.

import { test, expect } from '@playwright/test';

// Previous TypeScript data source retained for reference.
//
// We originally retrieved our appointment data from the TestData class.
// This line has been commented out because the test data is now loaded
// from an external CSV file instead.
// import TestData from '../../data/test-data';

// Import our reusable file helper.
//
// This helper contains functions for reading files, writing files,
// and parsing CSV data.
import fileHelper from '../helpers/file-helper';

// Import Node.js's native Path module.
//
// We'll use path.resolve() to build the full path to our CSV file.
import path from 'path';

// -----------------------------------------------------------------------------
// Previous implementation (retained for reference)
//
// The original version of this test retrieved appointment data from a
// TypeScript class.
//
// const makeApptTestData = TestData.makeAppointmentTestData();
// -----------------------------------------------------------------------------

// Build the full path to the appointment CSV file.
//
// process.cwd() returns the project's current working directory
// (the project root). We then append the relative path to the CSV file
// and use path.resolve() to generate the complete file path.
const csvFilePath = path.resolve(
    `${process.cwd()}/data/functional/make-aptmnt-test-data.csv`
);

// Read and parse the CSV file.
//
// fileHelper.readCSV() reads the CSV file, parses its contents,
// and returns an array of JavaScript objects.
//
// Each object represents one row of appointment data from the CSV file.
const makeApptTestData = fileHelper.readCSV(csvFilePath);

// Generate one Playwright test for every row contained in the CSV file.
//
// During each iteration, 'apptData' represents the current appointment
// dataset being used to generate the Playwright test.
//
// Everything inside this loop is repeated once for every row contained
// in the CSV file.
for (const apptData of makeApptTestData) {
    test.describe('Make appointment', () => {
        // The beforeEach() hook runs before every generated test.
        //
        // Regardless of which appointment dataset is being used, each test
        // begins by navigating to the application and logging in with valid
        // credentials.
        test.beforeEach('Login with valid creds', async ({ page }) => {
            // Navigate to the CURA Healthcare Service home page.
            await page.goto('https://katalon-demo-cura.herokuapp.com/');

            // Verify that the application loaded successfully.
            await expect(page).toHaveTitle('CURA Healthcare Service');
            await expect(page.locator('//h1')).toHaveText('CURA Healthcare Service');

            // Navigate to the login page.
            await page.getByRole('link', { name: 'Make Appointment' }).click();

            // Verify that the login page is displayed.
            await expect(page.getByText('Please login to make')).toBeVisible();

            // Log in using valid credentials.
            await page.getByLabel('Username').fill('John Doe');
            await page.getByLabel('Password').fill('ThisIsNotAPassword');
            await page.getByRole('button', { name: 'Login' }).click();

            // Retrieve all cookies currently stored in this page's browser context.
            //
            // The cookies are returned as an array of JavaScript objects.
            const loginCookies = await page.context().cookies();

            // Environment variables can only store strings.
            //
            // JSON.stringify() converts the cookie array into JSON-formatted
            // text so it can be stored in process.env.LOGIN_COOKIES.
            //
            // Because this assignment occurs inside a test worker, the value
            // is available only to code executing in that same worker process.
            process.env.LOGIN_COOKIES = JSON.stringify(loginCookies);

            // Verify that the login completed successfully.
            await expect(page.locator('h2')).toContainText('Make Appointment');
        });

        // Generate one Playwright test for the current appointment dataset.
        //
        // The testID property is included in the test name so the generated
        // Playwright and Allure reports clearly identify which CSV dataset
        // produced each test result.
        test(`${apptData.testID}: Should make an appointment with non-default values`, async ({ page }) => {
            // Display the serialized login cookies that were captured by the
            // beforeEach() hook for the current test execution.
            console.log(`>> Login cookies: ${process.env.LOGIN_COOKIES}`);

            // Select the Facility specified in the current dataset.
            await page.getByLabel('Facility').selectOption(apptData.facility);

            // Apply for hospital readmission.
            await page.getByRole('checkbox', { name: 'Apply for hospital readmission' }).check();

            // Select the Healthcare Program specified in the current dataset.
            await page.getByText(apptData.hcp).check();

            // Enter the Visit Date from the current dataset.
            await page.getByRole('textbox', { name: 'Visit Date (Required)' }).click();
            await page.getByRole('textbox', { name: 'Visit Date (Required)' }).fill(apptData.visitDt);
            await page.getByRole('textbox', { name: 'Visit Date (Required)' }).press('Enter');

            // Enter a comment.
            await page.getByRole('textbox', { name: 'Comment' }).click();
            await page
                .getByRole('textbox', { name: 'Comment' })
                .fill('This is a multi-line comment\ncaptured by Playwright codegen');

            // Submit the appointment.
            await page.getByRole('button', { name: 'Book Appointment' }).click();

            // Verify that the appointment was created successfully.
            await expect(page.locator('h2')).toContainText('Appointment Confirmation');
            await expect(page.getByRole('link', { name: 'Go to Homepage' })).toBeVisible();
        });

        // Additional appointment-related tests could be added here.
    });
}
