// ============================================================================
// This script demonstrates data-driven testing using a TypeScript data source.
//
// Rather than hard-coding test values directly into the test, we retrieve an
// array of appointment datasets from the TestData class. A separate Playwright
// test is automatically generated for each dataset.
// ============================================================================

// The code below was generated by initiating codegen,
// stopping the recording, manually navigating to the login page,
// logging in, and then starting the recording again.

import { test, expect } from '@playwright/test';
import TestData from '../../data/test-data';

// Call the static makeAppointmentTestData() method.
//
// The method returns an array containing three appointment datasets.
// Each object in the array represents one appointment scenario that will be
// executed as a separate Playwright test.
const makeApptTestData = TestData.makeAppointmentTestData();

// Loop through the array one appointment dataset at a time.
//
// During each iteration, 'apptData' represents the current appointment object.
// Everything inside this loop is repeated once for each dataset.
for (const apptData of makeApptTestData) {
    test.describe('Make appointment', () => {
        // The beforeEach() hook runs before every generated test.
        //
        // Regardless of which appointment dataset is being used, each test
        // begins by navigating to the application and logging in with valid
        // credentials.
        test.beforeEach('Login with valid creds', async ({ page }) => {
            // Navigate to the CURA Healthcare Service home page.
            await page.goto('https://katalon-demo-cura.herokuapp.com/');

            // Verify that the application loaded successfully.
            await expect(page).toHaveTitle('CURA Healthcare Service');
            await expect(page.locator('//h1')).toHaveText('CURA Healthcare Service');

            // Navigate to the login page.
            await page.getByRole('link', { name: 'Make Appointment' }).click();

            // Verify that the login page is displayed.
            await expect(page.getByText('Please login to make')).toBeVisible();

            // Log in using valid credentials.
            await page.getByLabel('Username').fill('John Doe');
            await page.getByLabel('Password').fill('ThisIsNotAPassword');
            await page.getByRole('button', { name: 'Login' }).click();

            // Retrieve all cookies currently stored in this page's browser context.
            //
            // The cookies are returned as an array of JavaScript objects.
            const loginCookies = await page.context().cookies();

            // Environment variables can only store strings.
            //
            // JSON.stringify() converts the cookie array into JSON-formatted text so it can
            // be stored in process.env.LOGIN_COOKIES.
            //
            // Because this assignment occurs inside a test worker, the value is available
            // only to code executing in that same worker process.
            process.env.LOGIN_COOKIES = JSON.stringify(loginCookies);

            // Text assertion to verify successful login
            await expect(page.locator('h2')).toContainText('Make Appointment');
        });

        // Generate one Playwright test for the current appointment dataset.
        //
        // The testID property is included in the test name so the generated
        // reports clearly identify which dataset produced each test result.
        test(`${apptData.testID}: Should make an appointment with non-default values`, async ({ page }) => {
            // Read and display the serialized login cookies that were captured by the
            // beforeEach() hook for the current test execution.
            console.log(`>> Login cookies: ${process.env.LOGIN_COOKIES}`);

            // Dropdown - Select the Facility specified in the current dataset.
            await page.getByLabel('Facility').selectOption(apptData.facility);

            // Apply for hospital readmission.
            await page.getByRole('checkbox', { name: 'Apply for hospital readmission' }).check();

            // Select the Healthcare Program specified in the current dataset.
            await page.getByText(apptData.hcp).check();

            // Enter the Visit Date from the current dataset.
            await page.getByRole('textbox', { name: 'Visit Date (Required)' }).click();
            await page.getByRole('textbox', { name: 'Visit Date (Required)' }).fill(apptData.visitDt);
            await page.getByRole('textbox', { name: 'Visit Date (Required)' }).press('Enter');

            // Enter a comment.
            await page.getByRole('textbox', { name: 'Comment' }).click();
            await page.getByRole('textbox', { name: 'Comment' }).fill('This is a multi-line comment\ncaptured by Playwright codegen');

            // Submit the appointment.
            await page.getByRole('button', { name: 'Book Appointment' }).click();

            // Verify that the appointment was created successfully.
            await expect(page.locator('h2')).toContainText('Appointment Confirmation');
            await expect(page.getByRole('link', { name: 'Go to Homepage' })).toBeVisible();
        });

        // Additional appointment-related tests could be added here.
    });
}
